window.DEFAULT_SITES = [
  {name:"豆包",        url:"https://www.doubao.com",            desc:"AI 助手",   cat:"ai"},
  {name:"ChatGPT",     url:"https://chatgpt.com",               desc:"OpenAI",    cat:"ai"},
  {name:"Claude",      url:"https://claude.ai",                 desc:"Anthropic", cat:"ai"},
  {name:"Kimi",        url:"https://kimi.moonshot.cn",          desc:"月之暗面",  cat:"ai"},
  {name:"DeepSeek",    url:"https://chat.deepseek.com",         desc:"深度求索",  cat:"ai"},
  {name:"通义千问",    url:"https://tongyi.aliyun.com",         desc:"阿里",      cat:"ai"},
  {name:"Gemini",      url:"https://gemini.google.com",         desc:"Google",    cat:"ai"},
  {name:"文心一言",    url:"https://yiyan.baidu.com",           desc:"百度",      cat:"ai"},
  {name:"哔哩哔哩",    url:"https://www.bilibili.com",          desc:"B站",       cat:"video"},
  {name:"YouTube",     url:"https://www.youtube.com",           desc:"YouTube",   cat:"video"},
  {name:"抖音",        url:"https://www.douyin.com",            desc:"短视频",    cat:"video"},
  {name:"快手",        url:"https://www.kuaishou.com",          desc:"短视频",    cat:"video"},
  {name:"腾讯视频",    url:"https://v.qq.com",                  desc:"视频",      cat:"video"},
  {name:"爱奇艺",      url:"https://www.iqiyi.com",             desc:"视频",      cat:"video"},
  {name:"优酷",        url:"https://www.youku.com",             desc:"视频",      cat:"video"},
  {name:"西瓜视频",    url:"https://www.ixigua.com",            desc:"视频",      cat:"video"},
  {name:"微博",        url:"https://weibo.com",                 desc:"社交",      cat:"social"},
  {name:"知乎",        url:"https://www.zhihu.com",             desc:"问答社区",  cat:"social"},
  {name:"小红书",      url:"https://www.xiaohongshu.com",       desc:"生活方式",  cat:"social"},
  {name:"豆瓣",        url:"https://www.douban.com",            desc:"书影音",    cat:"social"},
  {name:"贴吧",        url:"https://tieba.baidu.com",           desc:"兴趣社区",  cat:"social"},
  {name:"即刻",        url:"https://okjike.com",                desc:"兴趣社区",  cat:"social"},
  {name:"脉脉",        url:"https://maimai.cn",                 desc:"职场社交",  cat:"social"},
  {name:"微信",        url:"https://weixin.qq.com",             desc:"微信",      cat:"social"},
  {name:"GitHub",      url:"https://github.com",                desc:"代码托管",  cat:"dev"},
  {name:"Gitee",       url:"https://gitee.com",                 desc:"码云",      cat:"dev"},
  {name:"Stack Overflow", url:"https://stackoverflow.com",      desc:"技术问答",  cat:"dev"},
  {name:"掘金",        url:"https://juejin.cn",                 desc:"技术社区",  cat:"dev"},
  {name:"V2EX",        url:"https://www.v2ex.com",              desc:"技术社区",  cat:"dev"},
  {name:"菜鸟教程",    url:"https://www.runoob.com",            desc:"编程教程",  cat:"dev"},
  {name:"MDN",         url:"https://developer.mozilla.org",     desc:"Web 文档",  cat:"dev"},
  {name:"LeetCode",    url:"https://leetcode.cn",               desc:"刷题",      cat:"dev"},
  {name:"百度",        url:"https://www.baidu.com",             desc:"搜索",      cat:"news"},
  {name:"今日头条",    url:"https://www.toutiao.com",           desc:"资讯",      cat:"news"},
  {name:"澎湃",        url:"https://www.thepaper.cn",           desc:"新闻",      cat:"news"},
  {name:"36氪",        url:"https://36kr.com",                  desc:"科技商业",  cat:"news"},
  {name:"虎嗅",        url:"https://www.huxiu.com",             desc:"科技商业",  cat:"news"},
  {name:"网易新闻",    url:"https://news.163.com",              desc:"新闻",      cat:"news"},
  {name:"腾讯新闻",    url:"https://news.qq.com",               desc:"新闻",      cat:"news"},
  {name:"少数派",      url:"https://sspai.com",                 desc:"效率生活",  cat:"news"},
  {name:"淘宝",        url:"https://www.taobao.com",            desc:"购物",      cat:"shop"},
  {name:"京东",        url:"https://www.jd.com",                desc:"购物",      cat:"shop"},
  {name:"拼多多",      url:"https://www.pinduoduo.com",         desc:"购物",      cat:"shop"},
  {name:"闲鱼",        url:"https://www.goofish.com",           desc:"二手",      cat:"shop"},
  {name:"当当",        url:"https://www.dangdang.com",          desc:"图书",      cat:"shop"},
  {name:"苏宁易购",    url:"https://www.suning.com",            desc:"购物",      cat:"shop"},
  {name:"亚马逊",      url:"https://www.amazon.cn",             desc:"海外购",    cat:"shop"},
  {name:"什么值得买",  url:"https://www.smzdm.com",             desc:"比价",      cat:"shop"},
  {name:"智谱清言",    url:"https://chatglm.cn",                 desc:"免费额度",  cat:"ai"},
  {name:"讯飞星火",    url:"https://xinghuo.xfyun.cn",           desc:"免费额度",  cat:"ai"},
  {name:"腾讯元宝",    url:"https://yuanbao.tencent.com",       desc:"免费额度",  cat:"ai"},
  {name:"天工AI",      url:"https://www.tiangong.cn",           desc:"免费额度",  cat:"ai"},
  {name:"Perplexity",  url:"https://www.perplexity.ai",         desc:"免费版",    cat:"ai"},
  {name:"Copilot",     url:"https://copilot.microsoft.com",     desc:"免费额度",  cat:"ai"},
  {name:"海螺AI",      url:"https://hailuoai.com",              desc:"免费额度",  cat:"ai"},
  {name:"Poe",         url:"https://poe.com",                   desc:"多模型",    cat:"ai"},
  {name:"HuggingFace", url:"https://huggingface.co",            desc:"开源模型",  cat:"ai"},
  {name:"Replicate",   url:"https://replicate.com",             desc:"API 试用",  cat:"ai"},
  {name:"百度网盘",    url:"https://pan.baidu.com",             desc:"网盘",      cat:"pan"},
  {name:"阿里云盘",    url:"https://www.alipan.com",            desc:"网盘",      cat:"pan"},
  {name:"夸克网盘",    url:"https://pan.quark.cn",              desc:"网盘",      cat:"pan"},
  {name:"腾讯微云",    url:"https://www.weiyun.com",            desc:"网盘",      cat:"pan"},
  {name:"123云盘",     url:"https://www.123pan.com",            desc:"网盘",      cat:"pan"},
  {name:"蓝奏云",      url:"https://www.lanzoui.com",           desc:"网盘",      cat:"pan"},
  {name:"奶牛快传",    url:"https://cowtransfer.com",           desc:"传输",      cat:"pan"},
  {name:"天翼云盘",    url:"https://cloud.189.cn",              desc:"网盘",      cat:"pan"},
  {name:"Notion",      url:"https://www.notion.so",             desc:"笔记",      cat:"tool"},
  {name:"飞书",        url:"https://www.feishu.cn",             desc:"协作",      cat:"tool"},
  {name:"钉钉",        url:"https://www.dingtalk.com",          desc:"协作",      cat:"tool"},
  {name:"石墨文档",    url:"https://shimo.im",                  desc:"文档",      cat:"tool"},
  {name:"语雀",        url:"https://www.yuque.com",             desc:"文档",      cat:"tool"},
  {name:"腾讯文档",    url:"https://docs.qq.com",               desc:"文档",      cat:"tool"},
  {name:"金山文档",    url:"https://www.kdocs.cn",              desc:"文档",      cat:"tool"},
  {name:"ProcessOn",   url:"https://www.processon.com",         desc:"流程图",    cat:"tool"},
  {name:"Canva可画",   url:"https://www.canva.cn",              desc:"设计",      cat:"tool"},
  {name:"印象笔记",    url:"https://www.yinxiang.com",          desc:"笔记",      cat:"tool"},
  {name:"中国大学MOOC",url:"https://www.icourse163.org",        desc:"公开课",    cat:"study"},
  {name:"Coursera",    url:"https://www.coursera.org",          desc:"公开课",    cat:"study"},
  {name:"学堂在线",    url:"https://www.xuetangx.com",          desc:"公开课",    cat:"study"},
  {name:"网易公开课",  url:"https://open.163.com",              desc:"视频课",    cat:"study"},
  {name:"得到",        url:"https://www.dedao.cn",              desc:"知识付费",  cat:"study"},
  {name:"可汗学院",    url:"https://zh.khanacademy.org",        desc:"免费课程",  cat:"study"},
  {name:"多邻国",      url:"https://www.duolingo.com",          desc:"语言学习",  cat:"study"},
  {name:"TED",         url:"https://www.ted.com",               desc:"演讲",      cat:"study"},
  {name:"网易云音乐",  url:"https://music.163.com",             desc:"音乐",      cat:"media"},
  {name:"QQ音乐",      url:"https://y.qq.com",                  desc:"音乐",      cat:"media"},
  {name:"酷狗音乐",    url:"https://www.kugou.com",             desc:"音乐",      cat:"media"},
  {name:"喜马拉雅",    url:"https://www.ximalaya.com",          desc:"有声",      cat:"media"},
  {name:"芒果TV",      url:"https://www.mgtv.com",              desc:"视频",      cat:"media"},
  {name:"咪咕视频",    url:"https://www.miguvideo.com",         desc:"视频",      cat:"media"},
  {name:"央视网",      url:"https://www.cctv.com",              desc:"视频",      cat:"media"},
  {name:"搜狐视频",    url:"https://tv.sohu.com",               desc:"视频",      cat:"media"},
  {name:"即梦AI",      url:"https://jimeng.jianying.com",       desc:"AI 生图",   cat:"ai"},
  {name:"可灵AI",      url:"https://klingai.com",               desc:"AI 视频",   cat:"ai"},
  {name:"Vidu",        url:"https://www.vidu.studio",           desc:"AI 视频",   cat:"ai"},
  {name:"Luma",        url:"https://lumalabs.ai",               desc:"AI 视频",   cat:"ai"},
  {name:"Runway",      url:"https://runwayml.com",              desc:"AI 视频",   cat:"ai"},
  {name:"Midjourney",  url:"https://www.midjourney.com",        desc:"AI 绘图",   cat:"ai"},
  {name:"LiblibAI",    url:"https://www.liblib.art",            desc:"AI 绘图",   cat:"ai"},
  {name:"Suno",        url:"https://suno.com",                  desc:"AI 音乐",   cat:"ai"},
  {name:"剪映",        url:"https://www.capcut.cn",             desc:"视频剪辑",  cat:"ai"},
  {name:"腾讯智影",    url:"https://zhi.qq.com",                desc:"AI 创作",   cat:"ai"},
  {name:"文心一格",    url:"https://yige.baidu.com",            desc:"AI 绘图",   cat:"ai"},
  {name:"通义万相",    url:"https://wanxiang.aliyun.com",       desc:"AI 绘图",   cat:"ai"},
  {name:"1905电影网",  url:"https://www.1905.com",              desc:"电影",      cat:"video"},
  {name:"华数TV",      url:"https://www.wasu.cn",               desc:"视频",      cat:"video"},
  {name:"QQ",          url:"https://im.qq.com",                 desc:"即时通讯",  cat:"social"},
  {name:"LinkedIn",    url:"https://www.linkedin.com",          desc:"职场社交",  cat:"social"},
  {name:"X",           url:"https://x.com",                     desc:"社交",      cat:"social"},
  {name:"Facebook",    url:"https://www.facebook.com",          desc:"社交",      cat:"social"},
  {name:"Instagram",   url:"https://www.instagram.com",         desc:"社交",      cat:"social"},
  {name:"Telegram",    url:"https://telegram.org",              desc:"即时通讯",  cat:"social"},
  {name:"Discord",     url:"https://discord.com",               desc:"社群",      cat:"social"},
  {name:"Reddit",      url:"https://www.reddit.com",            desc:"社区",      cat:"social"},
  {name:"Quora",       url:"https://www.quora.com",             desc:"问答",      cat:"social"},
  {name:"TikTok",      url:"https://www.tiktok.com",            desc:"短视频",    cat:"social"},
  {name:"Soul",        url:"https://www.soulapp.cn",            desc:"社交",      cat:"social"},
  {name:"陌陌",        url:"https://www.immomo.com",            desc:"社交",      cat:"social"},
  {name:"和彩云",      url:"https://mcloud.139.com",            desc:"网盘",      cat:"pan"},
  {name:"115网盘",     url:"https://115.com",                   desc:"网盘",      cat:"pan"},
  {name:"迅雷网盘",    url:"https://pan.xunlei.com",            desc:"网盘",      cat:"pan"},
  {name:"文叔叔",      url:"https://www.wenshushu.cn",          desc:"传输",      cat:"pan"},
  {name:"AirPortal",   url:"https://airportal.cn",              desc:"传输",      cat:"pan"},
  {name:"PicGo",       url:"https://picgo.github.io",           desc:"图床工具",  cat:"pan"},
  {name:"CSDN",        url:"https://www.csdn.net",              desc:"技术社区",  cat:"dev"},
  {name:"博客园",      url:"https://www.cnblogs.com",           desc:"技术博客",  cat:"dev"},
  {name:"简书",        url:"https://www.jianshu.com",           desc:"写作社区",  cat:"dev"},
  {name:"思否",        url:"https://segmentfault.com",          desc:"技术问答",  cat:"dev"},
  {name:"51CTO",       url:"https://www.51cto.com",             desc:"技术社区",  cat:"dev"},
  {name:"开源中国",    url:"https://www.oschina.net",           desc:"开源社区",  cat:"dev"},
  {name:"InfoQ",       url:"https://www.infoq.cn",              desc:"技术媒体",  cat:"dev"},
  {name:"Docker Hub",  url:"https://hub.docker.com",            desc:"容器镜像",  cat:"dev"},
  {name:"npm",         url:"https://www.npmjs.com",             desc:"包管理",    cat:"dev"},
  {name:"PyPI",        url:"https://pypi.org",                  desc:"Python 包", cat:"dev"},
  {name:"GitLab",      url:"https://gitlab.com",                desc:"代码托管",  cat:"dev"},
  {name:"Google Colab",url:"https://colab.research.google.com", desc:"云端编程",  cat:"dev"},
  {name:"Replit",      url:"https://replit.com",                desc:"在线编程",  cat:"dev"},
  {name:"CodePen",     url:"https://codepen.io",                desc:"前端演示",  cat:"dev"},
  {name:"Codeforces",  url:"https://codeforces.com",            desc:"算法竞赛",  cat:"dev"},
  {name:"LeetCode国际",url:"https://leetcode.com",              desc:"刷题",      cat:"dev"},
  {name:"央视新闻",    url:"https://news.cctv.com",             desc:"新闻",      cat:"news"},
  {name:"人民日报",    url:"https://www.people.com.cn",         desc:"新闻",      cat:"news"},
  {name:"新华网",      url:"https://www.xinhuanet.com",         desc:"新闻",      cat:"news"},
  {name:"光明网",      url:"https://www.gmw.cn",                desc:"新闻",      cat:"news"},
  {name:"环球网",      url:"https://www.huanqiu.com",           desc:"新闻",      cat:"news"},
  {name:"参考消息",    url:"https://www.cankaoxiaoxi.com",      desc:"新闻",      cat:"news"},
  {name:"第一财经",    url:"https://www.yicai.com",             desc:"财经",      cat:"news"},
  {name:"财新",        url:"https://www.caixin.com",            desc:"财经",      cat:"news"},
  {name:"界面新闻",    url:"https://www.jiemian.com",           desc:"新闻",      cat:"news"},
  {name:"IT之家",      url:"https://www.ithome.com",            desc:"科技",      cat:"news"},
  {name:"快科技",      url:"https://www.mydrivers.com",         desc:"科技",      cat:"news"},
  {name:"爱范儿",      url:"https://www.ifanr.com",             desc:"科技",      cat:"news"},
  {name:"极客公园",    url:"https://www.geekpark.net",          desc:"科技",      cat:"news"},
  {name:"站长之家",    url:"https://www.chinaz.com",            desc:"站长",      cat:"news"},
  {name:"太平洋电脑网",url:"https://www.pconline.com.cn",       desc:"IT 资讯",   cat:"news"},
  {name:"ZOL",         url:"https://www.zol.com.cn",            desc:"IT 资讯",   cat:"news"},
  {name:"慕课网",      url:"https://www.imooc.com",             desc:"IT 课程",   cat:"study"},
  {name:"极客时间",    url:"https://time.geekbang.org",         desc:"IT 课程",   cat:"study"},
  {name:"Udemy",       url:"https://www.udemy.com",             desc:"在线课程",  cat:"study"},
  {name:"edX",         url:"https://www.edx.org",               desc:"在线课程",  cat:"study"},
  {name:"MIT OCW",     url:"https://ocw.mit.edu",               desc:"MIT 课程",  cat:"study"},
  {name:"微信读书",    url:"https://weread.qq.com",             desc:"阅读",      cat:"study"},
  {name:"蜻蜓FM",      url:"https://www.qingting.fm",           desc:"有声",      cat:"study"},
  {name:"荔枝FM",      url:"https://www.lizhi.fm",              desc:"有声",      cat:"study"},
  {name:"哔哩课堂",    url:"https://www.bilibili.com/cheese",   desc:"课程",      cat:"study"},
  {name:"国家智慧教育平台",url:"https://www.smartedu.cn",       desc:"教育平台",  cat:"study"},
  {name:"国美",        url:"https://www.gome.com.cn",           desc:"家电",      cat:"shop"},
  {name:"唯品会",      url:"https://www.vip.com",               desc:"特卖",      cat:"shop"},
  {name:"网易严选",    url:"https://you.163.com",               desc:"严选",      cat:"shop"},
  {name:"小米商城",    url:"https://www.mi.com",                desc:"小米",      cat:"shop"},
  {name:"华为商城",    url:"https://www.vmall.com",             desc:"华为",      cat:"shop"},
  {name:"苹果官网",    url:"https://www.apple.com.cn",          desc:"苹果",      cat:"shop"},
  {name:"1688",        url:"https://www.1688.com",              desc:"批发",      cat:"shop"},
  {name:"得物",        url:"https://www.dewu.com",              desc:"潮流",      cat:"shop"},
  {name:"识货",        url:"https://www.shihuo.cn",             desc:"比价",      cat:"shop"},
  {name:"eBay",        url:"https://www.ebay.com",              desc:"海淘",      cat:"shop"},
  {name:"iHerb",       url:"https://www.iherb.cn",              desc:"海淘",      cat:"shop"},
  {name:"优衣库",      url:"https://www.uniqlo.com",            desc:"服饰",      cat:"shop"},
  {name:"NIKE",        url:"https://www.nike.com.cn",           desc:"运动",      cat:"shop"},
  {name:"麦当劳",      url:"https://www.mcdonalds.com.cn",      desc:"餐饮",      cat:"shop"},
  {name:"肯德基",      url:"https://www.kfc.com.cn",            desc:"餐饮",      cat:"shop"},
  {name:"星巴克",      url:"https://www.starbucks.com.cn",      desc:"咖啡",      cat:"shop"},
  {name:"在线PS",      url:"https://www.uupoop.com",            desc:"图片处理",  cat:"tool"},
  {name:"稿定设计",    url:"https://www.gaoding.com",           desc:"在线设计",  cat:"tool"},
  {name:"创客贴",      url:"https://www.chuangkit.com",         desc:"在线设计",  cat:"tool"},
  {name:"Tampermonkey",url:"https://www.tampermonkey.net",      desc:"油猴脚本",  cat:"tool"},
  {name:"uTools",      url:"https://www.u.tools",               desc:"效率工具",  cat:"tool"},
  {name:"Everything",  url:"https://www.voidtools.com",         desc:"文件搜索",  cat:"tool"},
  {name:"Zotero",      url:"https://www.zotero.org",            desc:"文献管理",  cat:"tool"},
  {name:"Typora",      url:"https://typora.io",                 desc:"Markdown",  cat:"tool"},
  {name:"XMind",       url:"https://xmind.cn",                  desc:"思维导图",  cat:"tool"},
  {name:"滴答清单",    url:"https://www.dida365.com",           desc:"待办",      cat:"tool"},
  {name:"幕布",        url:"https://mubu.com",                  desc:"大纲笔记",  cat:"tool"},
  {name:"QQ邮箱",      url:"https://mail.qq.com",               desc:"邮箱",      cat:"mail"},
  {name:"163邮箱",     url:"https://mail.163.com",              desc:"邮箱",      cat:"mail"},
  {name:"Gmail",       url:"https://mail.google.com",           desc:"邮箱",      cat:"mail"},
  {name:"Outlook",     url:"https://outlook.com",               desc:"邮箱",      cat:"mail"},
  {name:"阿里邮箱",    url:"https://mail.aliyun.com",           desc:"邮箱",      cat:"mail"},
  {name:"139邮箱",     url:"https://mail.10086.cn",             desc:"邮箱",      cat:"mail"},
  {name:"企业微信邮箱",url:"https://work.weixin.qq.com",        desc:"企业邮箱",  cat:"mail"},
  {name:"ProtonMail",  url:"https://proton.me",                 desc:"加密邮箱",  cat:"mail"},
  {name:"Yandex Mail", url:"https://mail.yandex.com",           desc:"邮箱",      cat:"mail"},
  {name:"iCloud",      url:"https://www.icloud.com",            desc:"苹果邮箱",  cat:"mail"},
  {name:"Google翻译",  url:"https://translate.google.com",      desc:"翻译",      cat:"trans"},
  {name:"DeepL",       url:"https://www.deepl.com",             desc:"翻译",      cat:"trans"},
  {name:"有道翻译",    url:"https://fanyi.youdao.com",          desc:"翻译",      cat:"trans"},
  {name:"百度翻译",    url:"https://fanyi.baidu.com",           desc:"翻译",      cat:"trans"},
  {name:"彩云小译",    url:"https://fanyi.caiyunapp.com",       desc:"翻译",      cat:"trans"},
  {name:"欧路词典",    url:"https://www.eudic.net",             desc:"词典",      cat:"trans"},
  {name:"剑桥词典",    url:"https://dictionary.cambridge.org",  desc:"词典",      cat:"trans"},
  {name:"柯林斯词典",  url:"https://www.collinsdictionary.com", desc:"词典",      cat:"trans"},
  {name:"术语在线",    url:"https://www.termonline.cn",         desc:"术语",      cat:"trans"},
  {name:"Urban Dictionary",url:"https://www.urbandictionary.com",desc:"俚语词典", cat:"trans"},
  {name:"高德地图",    url:"https://www.amap.com",              desc:"地图",      cat:"map"},
  {name:"百度地图",    url:"https://map.baidu.com",             desc:"地图",      cat:"map"},
  {name:"腾讯地图",    url:"https://lbs.qq.com",                desc:"地图",      cat:"map"},
  {name:"Google 地图", url:"https://www.google.com/maps",       desc:"地图",      cat:"map"},
  {name:"铁路12306",   url:"https://www.12306.cn",              desc:"火车票",    cat:"map"},
  {name:"携程",        url:"https://www.ctrip.com",             desc:"旅行",      cat:"map"},
  {name:"飞猪",        url:"https://www.fliggy.com",            desc:"旅行",      cat:"map"},
  {name:"去哪儿",      url:"https://www.qunar.com",             desc:"旅行",      cat:"map"},
  {name:"同程旅行",    url:"https://www.ly.com",                desc:"旅行",      cat:"map"},
  {name:"滴滴出行",    url:"https://www.didiglobal.com",        desc:"出行",      cat:"map"},
  {name:"菜鸟",        url:"https://www.cainiao.com",           desc:"快递",      cat:"map"},
  {name:"顺丰速运",    url:"https://www.sf-express.com",        desc:"快递",      cat:"map"},
  {name:"美团",        url:"https://www.meituan.com",           desc:"本地生活",  cat:"life"},
  {name:"饿了么",      url:"https://www.ele.me",                desc:"外卖",      cat:"life"},
  {name:"大众点评",    url:"https://www.dianping.com",          desc:"本地生活",  cat:"life"},
  {name:"58同城",      url:"https://www.58.com",                desc:"分类信息",  cat:"life"},
  {name:"贝壳找房",    url:"https://www.ke.com",                desc:"房产",      cat:"life"},
  {name:"安居客",      url:"https://www.anjuke.com",            desc:"房产",      cat:"life"},
  {name:"链家",        url:"https://www.lianjia.com",           desc:"房产",      cat:"life"},
  {name:"转转",        url:"https://www.zhuanzhuan.com",        desc:"二手",      cat:"life"},
  {name:"瓜子二手车",  url:"https://www.guazi.com",             desc:"二手车",    cat:"life"},
  {name:"汽车之家",    url:"https://www.autohome.com.cn",       desc:"汽车",      cat:"life"},
  {name:"懂车帝",      url:"https://www.dongchedi.com",         desc:"汽车",      cat:"life"},
  {name:"妈妈网",      url:"https://www.mama.cn",               desc:"母婴",      cat:"life"},
  {name:"宝宝树",      url:"https://www.babytree.com",          desc:"母婴",      cat:"life"},
  {name:"中国天气网",  url:"https://www.weather.com.cn",        desc:"天气",      cat:"life"},
  {name:"墨迹天气",    url:"https://www.moji.com",              desc:"天气",      cat:"life"},
  {name:"支付宝",      url:"https://www.alipay.com",            desc:"支付",      cat:"fin"},
  {name:"招商银行",    url:"https://www.cmbchina.com",          desc:"银行",      cat:"fin"},
  {name:"工商银行",    url:"https://www.icbc.com.cn",           desc:"银行",      cat:"fin"},
  {name:"建设银行",    url:"https://www.ccb.com",               desc:"银行",      cat:"fin"},
  {name:"农业银行",    url:"https://www.abchina.com",           desc:"银行",      cat:"fin"},
  {name:"中国银行",    url:"https://www.boc.cn",                desc:"银行",      cat:"fin"},
  {name:"交通银行",    url:"https://www.bankcomm.com",          desc:"银行",      cat:"fin"},
  {name:"同花顺",      url:"https://www.10jqka.com.cn",         desc:"行情",      cat:"fin"},
  {name:"东方财富",    url:"https://www.eastmoney.com",         desc:"财经",      cat:"fin"},
  {name:"天天基金",    url:"https://fund.eastmoney.com",        desc:"基金",      cat:"fin"},
  {name:"雪球",        url:"https://xueqiu.com",                desc:"投资社区",  cat:"fin"},
  {name:"新浪财经",    url:"https://finance.sina.com.cn",       desc:"财经",      cat:"fin"},
  {name:"上海交易所",  url:"https://www.sse.com.cn",            desc:"上交所",    cat:"fin"},
  {name:"深圳交易所",  url:"https://www.szse.cn",               desc:"深交所",    cat:"fin"},
  {name:"中国人民银行",url:"https://www.pbc.gov.cn",            desc:"央行",      cat:"fin"},
  {name:"Steam",       url:"https://store.steampowered.com",    desc:"游戏平台",  cat:"game"},
  {name:"Epic",        url:"https://store.epicgames.com",       desc:"游戏平台",  cat:"game"},
  {name:"TapTap",      url:"https://www.taptap.cn",             desc:"手游",      cat:"game"},
  {name:"WeGame",      url:"https://www.wegame.com.cn",         desc:"游戏平台",  cat:"game"},
  {name:"暴雪战网",    url:"https://www.battle.net",            desc:"暴雪",      cat:"game"},
  {name:"原神官网",    url:"https://ys.mihoyo.com",             desc:"米哈游",    cat:"game"},
  {name:"米哈游",      url:"https://www.mihoyo.com",            desc:"米哈游",    cat:"game"},
  {name:"NGA",         url:"https://nga.cn",                    desc:"游戏社区",  cat:"game"},
  {name:"游民星空",    url:"https://www.gamersky.com",          desc:"游戏资讯",  cat:"game"},
  {name:"游侠网",      url:"https://www.ali213.net",            desc:"游戏资讯",  cat:"game"},
  {name:"3DM",         url:"https://www.3dmgame.com",           desc:"游戏资讯",  cat:"game"},
  {name:"Xbox",        url:"https://www.xbox.com",              desc:"微软游戏",  cat:"game"},
  {name:"PlayStation", url:"https://www.playstation.com",       desc:"索尼游戏",  cat:"game"},
  {name:"Nintendo",    url:"https://www.nintendo.com",          desc:"任天堂",    cat:"game"},
  {name:"Minecraft",   url:"https://www.minecraft.net",         desc:"我的世界",  cat:"game"},
  {name:"站酷",        url:"https://www.zcool.com.cn",          desc:"设计社区",  cat:"design"},
  {name:"花瓣",        url:"https://huaban.com",                desc:"灵感采集",  cat:"design"},
  {name:"Behance",     url:"https://www.behance.net",           desc:"设计社区",  cat:"design"},
  {name:"Dribbble",    url:"https://dribbble.com",              desc:"设计社区",  cat:"design"},
  {name:"Pinterest",   url:"https://www.pinterest.com",         desc:"灵感",      cat:"design"},
  {name:"Unsplash",    url:"https://unsplash.com",              desc:"免费图库",  cat:"design"},
  {name:"Pexels",      url:"https://www.pexels.com",            desc:"免费图库",  cat:"design"},
  {name:"Pixabay",     url:"https://pixabay.com",               desc:"免费图库",  cat:"design"},
  {name:"iconfont",    url:"https://www.iconfont.cn",           desc:"图标库",    cat:"design"},
  {name:"Font Awesome",url:"https://fontawesome.com",           desc:"图标库",    cat:"design"},
  {name:"千图网",      url:"https://www.58pic.com",             desc:"素材",      cat:"design"},
  {name:"包图网",      url:"https://ibaotu.com",                desc:"素材",      cat:"design"},
  {name:"摄图网",      url:"https://699pic.com",                desc:"素材",      cat:"design"},
  {name:"图虫创意",    url:"https://stock.tuchong.com",         desc:"图库",      cat:"design"},
  {name:"UI中国",      url:"https://www.ui.cn",                 desc:"UI 设计",   cat:"design"},
  {name:"优设",        url:"https://www.uisdc.com",             desc:"设计教程",  cat:"design"},
  {name:"BOSS直聘",    url:"https://www.zhipin.com",            desc:"招聘",      cat:"job"},
  {name:"前程无忧",    url:"https://www.51job.com",             desc:"招聘",      cat:"job"},
  {name:"智联招聘",    url:"https://www.zhaopin.com",           desc:"招聘",      cat:"job"},
  {name:"拉勾",        url:"https://www.lagou.com",             desc:"互联网招聘",cat:"job"},
  {name:"猎聘",        url:"https://www.liepin.com",            desc:"中高端招聘",cat:"job"},
  {name:"牛客",        url:"https://www.nowcoder.com",          desc:"校招",      cat:"job"},
  {name:"实习僧",      url:"https://www.shixiseng.com",         desc:"实习",      cat:"job"},
  {name:"应届生求职网",url:"https://www.yingjiesheng.com",      desc:"校招",      cat:"job"},
  {name:"国家大学生就业服务平台",url:"https://www.ncss.cn",     desc:"就业",      cat:"job"},
  {name:"看准网",      url:"https://www.kanzhun.com",           desc:"公司评价",  cat:"job"},
  {name:"丁香医生",    url:"https://www.dxy.com",               desc:"健康",      cat:"health"},
  {name:"好大夫在线",  url:"https://www.haodf.com",             desc:"就医",      cat:"health"},
  {name:"微医",        url:"https://www.guahao.com",            desc:"挂号",      cat:"health"},
  {name:"春雨医生",    url:"https://www.chunyuyisheng.com",     desc:"问诊",      cat:"health"},
  {name:"国家医保服务平台",url:"https://fuwu.nhsa.gov.cn",      desc:"医保",      cat:"health"},
  {name:"中国疾控中心",url:"https://www.chinacdc.cn",           desc:"疾控",      cat:"health"},
  {name:"国家卫健委",  url:"https://www.nhc.gov.cn",            desc:"卫健",      cat:"health"},
  {name:"百度健康",    url:"https://health.baidu.com",          desc:"健康",      cat:"health"},
  {name:"药房网",      url:"https://www.yaofang.cn",            desc:"药品",      cat:"health"},
  {name:"腾讯医典",    url:"https://www.dxy.cn",                desc:"医学科普",  cat:"health"},
  {name:"国家政务服务平台",url:"https://gjzwfw.www.gov.cn",     desc:"政务服务",  cat:"gov"},
  {name:"个人所得税",  url:"https://etax.chinatax.gov.cn",      desc:"个税",      cat:"gov"},
  {name:"国家企业信用信息公示系统",url:"https://www.gsxt.gov.cn",desc:"企业信用",  cat:"gov"},
  {name:"中国裁判文书网",url:"https://wenshu.court.gov.cn",     desc:"司法文书",  cat:"gov"},
  {name:"中国知网",    url:"https://www.cnki.net",              desc:"学术文献",  cat:"gov"},
  {name:"国家图书馆",  url:"https://www.nlc.cn",                desc:"图书馆",    cat:"gov"},
  {name:"中国政府网",  url:"https://www.gov.cn",                desc:"政府",      cat:"gov"},
  {name:"国家统计局",  url:"https://www.stats.gov.cn",          desc:"统计数据",  cat:"gov"},
  {name:"海关总署",    url:"https://www.customs.gov.cn",        desc:"海关",      cat:"gov"},
  {name:"国家知识产权局",url:"https://www.cnipa.gov.cn",        desc:"专利",      cat:"gov"},
  {name:"12315",       url:"https://www.12315.cn",              desc:"消费维权",  cat:"gov"},
  {name:"直播吧",      url:"https://www.zhibo8.cc",             desc:"体育直播",  cat:"sport"},
  {name:"虎扑",        url:"https://www.hupu.com",              desc:"体育社区",  cat:"sport"},
  {name:"懂球帝",      url:"https://www.dongqiudi.com",         desc:"足球",      cat:"sport"},
  {name:"腾讯体育",    url:"https://sports.qq.com",             desc:"体育",      cat:"sport"},
  {name:"新浪体育",    url:"https://sports.sina.com.cn",        desc:"体育",      cat:"sport"},
  {name:"央视体育",    url:"https://sports.cctv.com",           desc:"体育",      cat:"sport"},
  {name:"ESPN",        url:"https://www.espn.com",              desc:"体育",      cat:"sport"},
  {name:"NBA官网",     url:"https://www.nba.com",               desc:"篮球",      cat:"sport"},
  {name:"英超官网",    url:"https://www.premierleague.com",     desc:"足球",      cat:"sport"},
  {name:"体坛周报",    url:"https://www.titan24.com",           desc:"体育媒体",  cat:"sport"},
  {name:"马拉松报名",  url:"https://www.mararun.com",           desc:"跑步",      cat:"sport"},
  {name:"AcFun",       url:"https://www.acfun.cn",              desc:"弹幕视频",  cat:"anime"},
  {name:"腾讯动漫",    url:"https://ac.qq.com",                 desc:"漫画",      cat:"anime"},
  {name:"快看漫画",    url:"https://www.kuaikanmanhua.com",     desc:"漫画",      cat:"anime"},
  {name:"哔哩哔哩漫画",url:"https://manga.bilibili.com",        desc:"漫画",      cat:"anime"},
  {name:"动漫之家",    url:"https://www.dmzj.com",              desc:"漫画",      cat:"anime"},
  {name:"萌娘百科",    url:"https://zh.moegirl.org.cn",         desc:"ACG 百科",  cat:"anime"},
  {name:"Bangumi",     url:"https://bangumi.tv",                desc:"番剧记录",  cat:"anime"},
  {name:"动漫花园",    url:"https://www.dmhy.org",              desc:"字幕组",    cat:"anime"}
];
